package org.skepsun.kototoro.core.db

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.skepsun.kototoro.core.db.entity.MangaSourceEntity
import org.skepsun.kototoro.explore.data.SourcesSortOrder

/**
 * The real Kototoro schema and DAOs, generated by Room KMP, running on the bundled SQLite driver (the same driver
 * family iOS uses). Covers the paths that changed when the schema moved to commonMain: @RawQuery -> RoomRawQuery
 * (suspend and Flow), @Transaction open methods, @Upsert and @Insert(IGNORE).
 */
class MangaDatabaseDaoSmokeTest {

    private fun newDb(): MangaDatabase = Room.inMemoryDatabaseBuilder<MangaDatabase>()
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()

    private fun source(name: String, enabled: Boolean, sortKey: Int) = MangaSourceEntity(
        source = name, isEnabled = enabled, sortKey = sortKey, addedIn = 1, lastUsedAt = 0L, isPinned = false, cfState = 0,
    )

    @Test
    fun `RoomRawQuery suspend and Flow paths return filtered and ordered rows`() = runBlocking {
        val db = newDb()
        try {
            val dao = db.getSourcesDao()
            dao.insertIfAbsent(listOf(source("c", true, 3), source("a", true, 2), source("b", false, 1)))

            assertEquals(listOf("a", "c"), dao.findAll(enabledOnly = true, order = SourcesSortOrder.ALPHABETIC).map { it.source })
            assertEquals(
                listOf("b", "a", "c"),
                dao.observeAll(enabledOnly = false, order = SourcesSortOrder.MANUAL).first().map { it.source },
            )
        } finally {
            db.close()
        }
    }

    @Test
    fun `Transaction upsert and insert-ignore behave like the Android schema`() = runBlocking {
        val db = newDb()
        try {
            val dao = db.getSourcesDao()
            dao.insertIfAbsent(listOf(source("x", true, 1)))
            dao.insertIfAbsent(listOf(source("x", false, 99))) // IGNORE: the first row must survive
            assertEquals(1, dao.find("x")!!.sortKey)
            assertTrue(dao.find("x")!!.isEnabled)

            dao.setPinned("x", true, appVersionCode = 42) // @Transaction open suspend fun
            assertEquals(listOf("x"), dao.findAllPinned().map { it.source })

            dao.upsert(source("x", false, 7))
            val row = dao.find("x")!!
            assertFalse(row.isEnabled)
            assertEquals(7, row.sortKey)
            assertEquals(7, dao.getMaxSortKey())
        } finally {
            db.close()
        }
    }

    @Test
    fun `setPinned creates a missing source stamped with the injected app version`() = runBlocking {
        val db = newDb()
        try {
            val dao = db.getSourcesDao()
            dao.setPinned("new-source", true, appVersionCode = 123)
            val row = dao.find("new-source")!!
            assertEquals(123, row.addedIn) // was BuildConfig.VERSION_CODE before the DAO moved out of :app
            assertTrue(row.isPinned)
        } finally {
            db.close()
        }
    }
}
