package org.skepsun.kototoro.spikes.roomkmp

import androidx.room.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.skepsun.kototoro.core.db.MangaDatabase
import org.skepsun.kototoro.core.db.entity.MangaSourceEntity
import org.skepsun.kototoro.explore.data.SourcesSortOrder

/**
 * S2 smoke test: the real Kototoro schema + DAOs, generated by Room KMP, running on the bundled SQLite
 * driver (the same driver family iOS would use). Exercises the paths that changed in the KMP cut list:
 * @RawQuery -> RoomRawQuery (suspend + Flow), @Transaction open methods, @Upsert, @Insert(IGNORE).
 */
class RoomKmpSmokeTest {

    private fun newDb(): MangaDatabase = Room.inMemoryDatabaseBuilder<MangaDatabase>()
        .setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()

    private fun source(name: String, enabled: Boolean, sortKey: Int) = MangaSourceEntity(
        source = name, isEnabled = enabled, sortKey = sortKey, addedIn = 1, lastUsedAt = 0L, isPinned = false, cfState = 0,
    )

    @Test
    fun `RoomRawQuery suspend and Flow paths return filtered and ordered rows`() = runBlocking {
        val db = newDb()
        try {
            val dao = db.getSourcesDao()
            dao.insertIfAbsent(listOf(source("c", true, 3), source("a", true, 2), source("b", false, 1)))

            val enabledAlpha = dao.findAll(enabledOnly = true, order = SourcesSortOrder.ALPHABETIC)
            assertEquals(listOf("a", "c"), enabledAlpha.map { it.source })

            val allManual = dao.observeAll(enabledOnly = false, order = SourcesSortOrder.MANUAL).first()
            assertEquals(listOf("b", "a", "c"), allManual.map { it.source })
        } finally {
            db.close()
        }
    }

    @Test
    fun `Transaction upsert and insert-ignore behave like the Android schema`() = runBlocking {
        val db = newDb()
        try {
            val dao = db.getSourcesDao()
            dao.insertIfAbsent(listOf(source("x", true, 1)))
            dao.insertIfAbsent(listOf(source("x", false, 99))) // IGNORE: the first row must survive
            assertEquals(1, dao.find("x")!!.sortKey)
            assertTrue(dao.find("x")!!.isEnabled)

            dao.setPinned("x", true) // @Transaction open suspend fun
            assertEquals(listOf("x"), dao.findAllPinned().map { it.source })

            dao.upsert(source("x", false, 7))
            val row = dao.find("x")!!
            assertFalse(row.isEnabled)
            assertEquals(7, row.sortKey)
            assertEquals(7, dao.getMaxSortKey())
        } finally {
            db.close()
        }
    }
}
