package org.skepsun.kototoro.reader.core

/**
 * Immutable per-frame rendering contract generated by `ReaderCore` and consumed by `ReaderRenderer`.
 *
 * Conforms to ADR 0002 Principle: "ReaderCore owns semantics; Renderer owns presentation."
 * Contains zero decoded pixel data or image loader references.
 */
data class ReaderFrame(
    val viewport: ReaderViewport,
    val visibleNodes: List<VisibleNode>,
    val progress: ReaderProgressSnapshot = ReaderProgressSnapshot.from(viewport, visibleNodes),
)
